### ISSUE TITLE
UBS API endpoints resource

### ISSUE THREAD

**Issue by cosmincc** [Che4ter/UBStoYNAB#2]
Where are the API endpoints coming from?
Is there documentation or was it reverse engineered?

Reason I'm asking is that logging it with the Access Card every time is bothersome. I'd like to explore perhaps there is a way to have QR code generated for access app or use password (with lower capabilities).

**Comment by Che4ter** [comment]
The enpoints were recorded from the android ebanking app.  But I think they implemented certificate pinning in the mean time, so it's harder to observe the traffic.

**Comment by fr34k8** [comment]
@Che4ter can you update the code to (c)atch the latest changes ?

**Comment by Che4ter** [comment]
I'm sorry I can't. I'm no longer a customer of UBS therefore I don't have access any more.
